# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name': '城市表', 'verbose_name_plural': '城市表'},
        ),
    ]
